# cargo-deny configuration: license and vulnerability policy

[advisories]
# Use defaults (vulns fail). Customize by adding entries to ignore.
ignore = []

[licenses]
# Allowed SPDX license identifiers
allow = [
  "MIT",
  "Apache-2.0",
  "ISC",
  "CC0-1.0",
  "Unicode-DFS-2016"
]
confidence-threshold = 0.8

[licenses.private]
ignore = false
registries = ["https://github.com/rust-lang/crates.io-index"]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
deny = []
allow = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
