tag-prefix = "v"
tag-name = "v{{version}}"
push = true
sign-tag = false
sign-commit = false

# Disable publish/verify in local env; CI can handle artifacts
publish = false
verify = false
owners = []

# Commit message for the release commit
pre-release-commit-message = "chore(release): v{{version}}"

# Allow running from a clean tree only
allow-branch = ["main", "master"]
